# Generated by Django 3.0.6 on 2020-06-16 12:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Enter the agent's name", max_length=50)),
                ('status', models.NullBooleanField(help_text='escolha seu status')),
                ('env', models.CharField(max_length=20)),
                ('version', models.CharField(help_text='Enter the version', max_length=5)),
                ('address', models.GenericIPAddressField(protocol='IPV4', verbose_name='Agent IP Addess')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a group', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the user', max_length=50)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(help_text='Enter your email adress', max_length=254)),
                ('password', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(8)], verbose_name='User Password')),
            ],
        ),
        migrations.CreateModel(
            name='GroupUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this agent', primary_key=True, serialize=False)),
                ('group_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Group')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.User')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this agent', primary_key=True, serialize=False)),
                ('level', models.CharField(blank=True, choices=[('C', 'Critical'), ('D', 'Debug'), ('E', 'Error'), ('W', 'Warning'), ('I', 'Info')], default='E', help_text="Enter the events's level", max_length=1)),
                ('data', models.TextField(help_text='Describe the data', max_length=1000)),
                ('filed', models.NullBooleanField()),
                ('date', models.DateField(blank=True, null=True)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Agent')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.User')),
            ],
        ),
    ]
