# Generated by Django 3.0.6 on 2020-06-16 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200616_1011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupuser',
            name='group_id',
        ),
        migrations.RemoveField(
            model_name='groupuser',
            name='user_id',
        ),
        migrations.AddField(
            model_name='groupuser',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Group'),
        ),
        migrations.AddField(
            model_name='groupuser',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.User'),
        ),
    ]
