# Generated by Django 3.0.6 on 2020-06-16 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200616_1032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='filed',
            new_name='arquivado',
        ),
    ]
